### ISSUE TITLE
Can't Access S3

### ISSUE THREAD

**Issue by nsaud01** [techcto/datacenter#6]
Looks like the S3 bucket is no longer accessible. I'm getting the following error:

`S3 error: The specified bucket does not exist For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html`

**Comment by techcto** [comment]
It's been awhile, been meaning to come back to this project.  Where are you seeing this error?

**Comment by Kynth** [comment]
The links in the readme to launch a stack point to:

`https://s3.amazonaws.com/techto-datacenter/aws/rancher-ha-cluster.yaml`

Should these be?

`https://s3.amazonaws.com/rancher-aws/aws/rancher-ha-cluster.yaml`

**Comment by techcto** [comment]
You are correct.  I have not ran the project in a few months.  Someone else did with some luck.  This was originally started for Rancher 2 and then ported over to 3.  I do plan on finishing this, so please keep me updated on your use-case and I will try to help if possible.

**Comment by techcto** [comment]
I just pushed update.
